create table owner
(
    id         bigint generated by default as identity (maxvalue 99999999)
        constraint "Owner_pk"
            primary key,
    name       varchar not null,
    birth_date date
);

alter table owner
    owner to markhvostenko;

create table cat
(
    id         bigint generated by default as identity (maxvalue 99999999)
        constraint cat_pk
            primary key,
    name       varchar not null,
    breed      varchar,
    owner_id   bigint  not null
        constraint cat_owner_id_fk
            references owner,
    color      color,
    birth_date date
);

alter table cat
    owner to markhvostenko;

create table cat_friend
(
    id            bigint generated by default as identity (maxvalue 9999999)
        constraint cat_friend_pk
            primary key,
    cat_id        bigint not null
        constraint cat_friend_cat_1_fk
            references cat,
    cat_friend_id bigint
        constraint cat_friend_cat_2_fk
            references cat
);

alter table cat_friend
    owner to markhvostenko;