create table role
(
    id   integer generated always as identity (maxvalue 99999999)
        primary key,
    name varchar(255)
);

alter table role
    owner to postgres;

create table users
(
    id       bigint generated always as identity (maxvalue 99999999)
        constraint user_pk
            primary key,
    username varchar not null,
    password varchar not null
);

alter table users
    owner to markhvostenko;

create table owner
(
    id         bigint generated by default as identity (maxvalue 99999999)
        constraint "Owner_pk"
            primary key,
    name       varchar not null,
    birth_date date,
    user_id    bigint
        constraint owner_user_fk
            references users,
    username   varchar
);

alter table owner
    owner to markhvostenko;

create type color as enum ('brown', 'black', 'white', 'orange', 'grey', 'orange_white', 'black_white');

create table cat
(
    id         bigint generated by default as identity (maxvalue 99999999)
        constraint cat_pk
            primary key,
    name       varchar not null,
    breed      varchar,
    owner_id   bigint  not null
        constraint cat_owner_id_fk
            references owner,
    color      color,
    birth_date date
);

alter table cat
    owner to markhvostenko;

create table cat_friend
(
    id            bigint generated by default as identity (maxvalue 9999999)
        constraint cat_friend_pk
            primary key,
    cat_id        bigint not null
        constraint cat_friend_cat_1_fk
            references cat,
    cat_friend_id bigint
        constraint cat_friend_cat_2_fk
            references cat
);

alter table cat_friend
    owner to markhvostenko;

create table users_roles
(
    user_id bigint  not null
        constraint user_fk
            references users,
    role_id integer not null
        constraint role_fk
            references role,
    primary key (user_id, role_id)
);

alter table users_roles
    owner to postgres;